# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  frontend_build_and_test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}
          - v1-dependencies
      - run:
          name: install
          command: cd web/big-data-ui; yarn install
      - run:
          name: install karma
          command: cd web/big-data-ui; yarn add karma
      - run:
          name: run unit tests frontend
          command: cd web/big-data-ui; ./node_modules/karma/bin/karma start test/unit/karma.conf.js --single-run || true 
          environment:
            JUNIT_REPORT_PATH: /junit
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: web/big-data-ui/test/unit/junit
      - store_artifacts:
          path: web/big-data-ui/test/unit/junit
      - store_artifacts:
          path: web/big-data-ui/test/unit/coverage
      - save_cache:
          paths:
            - ./web/big-data-ui/.cache/yarn
          key: v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}


  backend_build_and_test:
    docker:
      # specify the version you desire here
      - image: maven:3.5.0-jdk-8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run unit tests backend
          command: cd backendRestDraft/; mvn test jacoco:report
      - store_test_results:
          path: backendRestDraft/target/site/jacoco
      - store_artifacts:
          path: backendRestDraft/target/site/jacoco
      - run:
          name: compile
          command: cd backendRestDraft/; mvn compile
      - run:
          name: clean install
          command: cd backendRestDraft/; mvn clean install

  frontend_deploy:
    docker:
      # docker image with aws and node version 8.7 preinstalled!
      - image: andrasszell/circleci-node-aws:8.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}
          - v1-dependencies
      - run:
          name: install
          command: cd web/big-data-ui; yarn install
      - run:
          name: create build
          command: cd web/big-data-ui; yarn run build
      - save_cache:
          paths:
            - ./web/big-data-ui/.cache/yarn
          key: v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}
      - run:
          name: Deploy Frontend to AWS
          working_directory: /
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              aws s3 sync ~/repo/web/big-data-ui/dist s3://pretrendrfrontend/ --region us-east-2 --acl public-read --delete
              echo "Deployed to production";
            else
              aws s3 sync ~/repo/web/big-data-ui/dist s3://pretrendrfrontendstaging/ --region us-east-2 --acl public-read --delete
              echo "deployed to staging";
            fi

  backend_deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy to AWS
          working_directory: ~/repo
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              chmod +x ./architecture/deployment/deploy_prod.sh
              sudo sh ./architecture/deployment/deploy_prod.sh -y
              echo "Deployed to production";
            else
              chmod +x ./architecture/deployment/deploy_staging.sh
              sudo sh ./architecture/deployment/deploy_staging.sh -y
              echo "Deployed to test";
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - frontend_build_and_test
      - backend_build_and_test
      - frontend_deploy:
          requires:
            - frontend_build_and_test
          filters:
            branches:
              only:
                - develop
                - master
      - backend_deploy:
          requires:
            - backend_build_and_test
          filters:
            branches:
              only:
                - develop
                - master
