# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/web

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/big-data-ui/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: install
          command: cd web/big-data-ui; yarn install

      - run: 
          name: install karma
          command: cd web/big-data-ui; yarn add karma

      - save_cache:
          paths:
            - ./web/big-data-ui/node_modules
          key: v1-dependencies-{{ checksum "web/big-data-ui/package.json" }}
        
      # run tests!
      #- run: cd web/big-data-ui; yarn run unit

  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: 
          name: install
          command: cd web/big-data-ui; yarn install
      - run: 
          name: install karma
          command: cd web/big-data-ui; yarn add karma
      - run: 
          name: unit
          command: cd web/big-data-ui; ./node_modules/karma/bin/karma start test/unit/karma.conf.js --single-run
          environment:
            JUNIT_REPORT_PATH: /junit
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: web/big-data-ui/test/unit/junit
      - store_artifacts:
          path: web/big-data-ui/test/unit/junit
      - store_artifacts:
          path: web/big-data-ui/test/unit/coverage


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build