# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: maven:3.5.0-jdk-8
      - image: circleci/node:7.10
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-workflows

  build_and_test_backend:
    docker:
      # specify the version you desire here
      - image: maven:3.5.0-jdk-8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/circleci-workflows
      #- run:
      #    name: install maven
      #    command: cd backendRestDraft/; sudo apt-get update -y; sudo apt-get install maven
      - run:
          name: run unit tests backend
          command: cd backendRestDraft/; mvn test

  build_and_test_frontend:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/circleci-workflows

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}
          - v1-dependencies
      - run:
          name: install
          command: cd web/big-data-ui; yarn install
      - run:
          name: install karma
          command: cd web/big-data-ui; yarn add karma

      - run:
          name: run unit tests
          command: cd web/big-data-ui; ./node_modules/karma/bin/karma start test/unit/karma.conf.js --single-run
          environment:
            JUNIT_REPORT_PATH: /junit
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: web/big-data-ui/test/unit/junit
      - store_artifacts:
          path: web/big-data-ui/test/unit/junit
      - store_artifacts:
          path: web/big-data-ui/test/unit/coverage

      - save_cache:
          paths:
            - ./web/big-data-ui/.cache/yarn
          key: v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}

  deploy_live:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}
          - v1-dependencies
      - run:
          name: install
          command: cd web/big-data-ui; yarn install
      - run:
          name: create build
          command: cd web/big-data-ui; yarn run build
      - run:
          name: install java sdk 8
          command: cd backendRestDraft/; sudo add-apt-repository ppa:webupd8team/java; sudo apt-get update; sudo apt-get install oracle-java8-installer
      - run:
          name: install maven
          command: cd backendRestDraft/; sudo apt-get update -y; sudo apt-get install maven
      - run:
          name: clean install backend
          command: cd backendRestDraft/; sudo mvn install; sudo mvn clean install
      - run:
          name: Install aws cli and deploy to aws
          working_directory: /
          command: |
            sudo apt-get -y -qq install awscli
            aws s3 sync ~/repo/web/big-data-ui/dist s3://pretrendrfrontend/ --delete

  deploy_staging:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/big-data-ui/yarn.lock" }}
          - v1-dependencies
      - run:
          name: install java sdk 8
          command: cd backendRestDraft/; sudo add-apt-repository ppa:webupd8team/java; sudo apt-get update; sudo apt-get install oracle-java8-installer
      - run:
          name: install maven
          command: cd backendRestDraft/; sudo apt-get update -y; sudo apt-get install maven
      - run:
          name: clean install backend
          command: cd backendRestDraft/; sudo mvn install; sudo mvn clean install
      - run:
          name: install
          command: cd web/big-data-ui; yarn install
      - run:
          name: create build
          command: cd web/big-data-ui; yarn run build
      - run:
          name: Install aws cli and deploy to aws
          working_directory: /
          command: |
            sudo apt-get -y -qq install awscli
            aws s3 sync ~/repo/web/big-data-ui/dist s3://pretrendrfrontendstaging.s3-website.us-east-2/ --delete


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build_and_test_backend:
          requires:
            - checkout_code
      - build_and_test_frontend:
          requires:
            - checkout_code
            - build_and_test_backend
      - deploy_live:
          requires:
            - build_and_test_frontend
          filters:
            branches:
              only:
                - master
      - deploy_staging:
          requires:
            - build_and_test_frontend
          filters:
            branches:
              only:
                - develop
